tap "fluxcd/tap"
tap "gbernady/tap"

brew "ansible"
brew "ansible-lint"
brew "aria2"
brew "asitop"
brew "clamav"
brew "cloc"
brew "cmake"
brew "exiftool"
brew "git"
brew "go"
brew "helm"
brew "jq"
brew "kepubify"
brew "kind"
brew "kubebuilder"
brew "kubernetes-cli"
brew "kubeseal"
brew "kustomize"
brew "make"
brew "mas"
brew "nmap"
brew "rustup-init"
brew "shellcheck"
brew "sqlite"
brew "svn"
brew "trivy"
brew "vim"
brew "watch"
brew "webp"
brew "wget"
brew "yamllint"
brew "ykman"
brew "fluxcd/tap/flux"
brew "gbernady/tap/git-credential-op"

cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "brave-browser"
cask "charles"
cask "coconutbattery"
cask "daisydisk"
cask "dash"
cask "discord"
cask "docker"
cask "firefox@developer-edition"
cask "font-open-sans"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "freecad"
cask "gog-galaxy"
cask "gpg-suite-no-mail"
cask "iina"
cask "keepassxc"
cask "keka"
cask "little-snitch"
cask "openttd"
cask "raspberry-pi-imager"
cask "rwts-pdfwriter"
cask "secretive"
cask "signal"
cask "slack"
cask "sourcetree"
cask "steam"
cask "transmission"
cask "utm"
cask "visual-studio-code"
cask "xld"
cask "yubico-yubikey-manager"
cask "zoom"
cask "sony-ps-remote-play"
cask "iterm2@beta"

mas "AdGuard for Safari", id: 1440147259
mas "Apple Configurator", id: 1037126344
mas "Developer", id: 640199958
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Poolsuite FM", id: 1514817810
mas "Reeder", id: 1529448980
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835

vscode "DavidAnson.vscode-markdownlint"
vscode "github.copilot"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "shardulm94.trailing-spaces"
vscode "tamasfe.even-better-toml"
vscode "teabyii.ayu"
vscode "tsandall.opa"
vscode "weaveworks.vscode-gitops-tools"
